### PR TITLE
Notebook for psf-photometry in crowded fields

### PR DESCRIPTION
**Pull request by mirca**

### CODE REVIEW

**Comment by mirca** [comment]
ping: @hamogu, @eteq, @bsipocz

**Comment by larrybradley** [comment]
@mirca Thanks.  For minor commit changes on the same file, you should be using "git commit --amend".  I also suggest that these commits get squashed into one commit before merging (notebooks don't diff well).

**Comment by mirca** [comment]
@larrybradley Thanks Larry. Commits squashed xD

**Comment by hamogu** [comment]
These comments are not really on the code, but looking at this notebook as part of the documentation. So, I looked at the wording on sentences, spelling etc., and where a little more explanation might be useful.

artificialy created -> simulated
have a known Gaussian Model -> have a Gaussian PSF
in several places: psf -> PSF ? I usually see it in capital letters, but not sure why
 an DAOPhotPSFPhotometry object -> a (not an)
this warning let -> lets us know

cell [6]: print(result_tab) -> astropy.table.Table objects have a __repr__html__ method that get called automatically if you just write "result_tab" without the "print". Then, you get an html formatted tables that looks a lot better in the browser than the console-style print. 

photometry with fixed positions: Say why this is relevant, e.g. This is useful, if all stellar positions are already known with a very high accuracy. In this case, we can fix the positions and reduce the number of parameters that are varied in the fit, making the fit faster and  reducing the number of local minima that fit could end up in.

cell [12]: needs some axis labels and a bigger font size of the numbers on the axis. Also, it needs some text like: Here, we compare the fitted flux with the simulated flux that we put in. The plot shows ... say that is works ... 
Also, a plot like `plt.scatter(starlist['flux'], result_tab['flux_fit']-starlist['flux'])` would be useful to see how the error depends on the source flax (I would expect brighter sources to be more accurate).

**Comment by mirca** [comment]
@hamogu Does that sound good?

**Comment by hamogu** [comment]
I have two more small things that I missed last time. Otherwise it's fine!

stars have a Gaussien model -> the PSF of a star has a Gaussian shape (the star does not "have" a model in the same sense as you "have" money or you "have"  time. The star is "described" by a model or the "PSF has a shape").

 "suboptimal" values may vary according to the data. -> suboptimal should be "optimal". The user needs to know that the optimal values vary. "Suboptimal" = "not optimal". Technically, it's entirely possible to find values that are not optimal for anything (e.g. PSF radius = 1e34), but that's not what you want to say here.

**Comment by hamogu** [comment]
@larrybradley comment about squashing commits because the diff between two notebooks is always very large still applies, but you can do that when everything else is ready, just before this PR is merged. No need to deal with that after every typo.

**Comment by mirca** [comment]
@hamogu Thanks!!

**Comment by eteq** [comment]
@mirca - OK, I had a look at this and I noticed tow things:
* I see most of your text starts with  `#####` - there's no need for that, when writing text you can just use the regular markdown  text mode (with a newline between it and the title line, if relevant).
* When talking about specific variables or classes or the like, use backticks (`` ` ``) around them, and then they will render in a font appropriate for a code identifier.  This makes it easier for readers to tell what's referring to a particular variable and what is regular prose.

I found it easy to do these updates while reading the notebook, though, so I created a PR against your branch to fix those.  If that looks good to you, feel free to merge it, at which point I think *this* is ready to go in!

**Comment by mirca** [comment]
@eteq done! =D

**Comment by eteq** [comment]
Alright looks good then.  Merging!

**Pull request merged**
